using Microsoft.CodeAnalysis.CSharp.Syntax;
using KitX.Core.Contract.Workflow;
using Serilog;
using KitX.Core.Workflow.Pipeline;
using KitX.Core.Workflow.CFG;
using KitX.Core.Workflow.BlockScripting;

namespace KitX.Core.Workflow.BuiltinFunctions
{
    public class CreateWorkflowFunction : IBuiltinFunctionDefinition
    {
        public string FunctionName => "CreateWorkflow";
        public string DisplayName => "Create Workflow";
        public bool IsFlowControl => false;
        public bool IsNonExtractable => true;
        public CFGStatementKind StatementKind => CFGStatementKind.Expression;
        public double NodeWidth => 180;
        public double NodeHeight => 80;

        public IReadOnlyList<PinDescriptor> InputPins => [
            new("Exec", PinType.Execution, 20),
            new("Name", PinType.String, 35),
            new("Source", PinType.String, 35)
        ];

        public IReadOnlyList<PinDescriptor> OutputPins => [
            new("Exec", PinType.Execution, 20),
            new("Return", PinType.String, 40)
        ];

        public BlockStatement? ExtractStatement(InvocationExpressionSyntax invoke, int lineNumber, string? exprText) => null;

        public List<CFGStatement> FormatInvocation(
            InvocationExpressionSyntax invoke, string blockName,
            PipelineContext context, string? assignedVar)
        {
            var args = invoke.ArgumentList.Arguments.Select(a => a.Expression.ToString()).ToList();
            return [new CFGStatement
            {
                BlockName = blockName,
                Kind = CFGStatementKind.Expression,
                FunctionName = FunctionName,
                Arguments = args,
                OriginalExpression = invoke.ToString(),
                SourceLine = 0,
            }];
        }

        public BlueprintNode ConfigureNode(BlueprintNode node, CFGStatement stmt)
        {
            if (node is BuiltinFunctionNode bfn && stmt.Arguments?.Count > 0)
                bfn.Properties["Name"] = stmt.Arguments[0];
            return node;
        }

        public BlockStatement? ToStatement(BlueprintNode node, INodeExportHelper helper)
        {
            var name = helper.GetInputValue(node, "Name");
            var source = helper.GetInputValue(node, "Source");
            return new ExpressionStatement
            {
                Expression = $"{FunctionName}({name}, {source})",
                SourceCode = $"{FunctionName}({name}, {source});",
                LineNumber = 1
            };
        }

        public IEnumerable<OutputArmDescriptor> GetOutputArms() => [];
    }
}

namespace KitX.Core.Workflow.BlockScripting
{
    public partial class BlockScriptExecutionGlobals
    {
        public string CreateWorkflow(string name, string blockScriptSource)
        {
            if (string.IsNullOrEmpty(name) || string.IsNullOrEmpty(blockScriptSource)) return "";
            if (!DI.ServiceHost.IsInitialized) return "";
            try
            {
                var storage = DI.ServiceHost.GetRequiredService<IWorkflowStorageService>();
                var workflowId = Guid.NewGuid().ToString();
                var kcsData = new KcsFileFormat
                {
                    Id = workflowId,
                    Name = name,
                    CreatedTime = DateTime.UtcNow,
                    LastModifiedTime = DateTime.UtcNow,
                    UseBlockMode = true,
                    BlockScriptSource = blockScriptSource,
                    TriggerType = "Manual",
                    Author = "AI Assistant",
                    Description = "Workflow generated by KitX AI Assistant"
                };

                storage.SaveWorkflowDataAsync(workflowId, kcsData).GetAwaiter().GetResult();
                Log.Information("[BlockScriptGlobals] CreateWorkflow: {Id} '{Name}'", workflowId, name);
                return workflowId;
            }
            catch (Exception ex)
            {
                Log.Error(ex, "[BlockScriptGlobals] CreateWorkflow failed for '{Name}'", name);
                return "";
            }
        }
    }
}
