using KitX.Core.Contract.Workflow;
using Serilog;
using KitX.Workflow.Conversion;
using KitX.Workflow.CFG;
using KitX.Workflow.BlockScripting;
using KitX.Workflow.Models;

namespace KitX.Workflow.BuiltinFunctions
{
    public class CreateWorkflowFunction : IBuiltinFunctionDefinition
    {
        public string FunctionName => "CreateWorkflow";
        public string DisplayName => "Create Workflow";
        public bool IsNonExtractable => false; // Value-producing (has Return pin) â€?can be nested as an expression

        public IReadOnlyList<PinDescriptor> InputPins => [
            new("Exec", PinType.Execution, 20),
            new("Name", PinType.String, 35),
            new("Source", PinType.String, 35)
        ];

        public IReadOnlyList<PinDescriptor> OutputPins => [
            new("Exec", PinType.Execution, 20),
            new("Return", PinType.String, 40)
        ];
    }
}

namespace KitX.Workflow.BlockScripting
{
    public partial class BlockScriptExecutionGlobals
    {
        public string CreateWorkflow(string name, string blockScriptSource)
        {
            if (string.IsNullOrEmpty(name) || string.IsNullOrEmpty(blockScriptSource)) return "";
            if (!ServiceLocator.IsInitialized) return "";
            try
            {
                var storage = ServiceLocator.GetRequiredService<IWorkflowStorageService>();
                var workflowId = Guid.NewGuid().ToString();
                var kcsData = new KcsFileFormat
                {
                    Id = workflowId,
                    Name = name,
                    CreatedTime = DateTime.UtcNow,
                    LastModifiedTime = DateTime.UtcNow,
                    UseBlockMode = true,
                    BlockScriptSource = blockScriptSource,
                    Author = "AI Assistant",
                    Description = "Workflow generated by KitX AI Assistant"
                };

                storage.SaveWorkflowDataAsync(workflowId, kcsData).GetAwaiter().GetResult();
                Log.Information("[BlockScriptGlobals] CreateWorkflow: {Id} '{Name}'", workflowId, name);
                return workflowId;
            }
            catch (Exception ex)
            {
                Log.Error(ex, "[BlockScriptGlobals] CreateWorkflow failed for '{Name}'", name);
                return "";
            }
        }
    }
}
