using KitX.Core.Contract.Workflow;
using Serilog;
using KitX.Workflow.Conversion;
using KitX.Workflow.CFG;
using KitX.Workflow.BlockScripting;
using KitX.Workflow.Models;

namespace KitX.Workflow.BuiltinFunctions
{
    public class CreateWorkflowFunction : IBuiltinFunctionDefinition
    {
        public string FunctionName => "CreateWorkflow";
        public string DisplayName => "Create Workflow";
        public bool IsNonExtractable => false; // Value-producing (has Return pin) — can be nested as an expression

        public IReadOnlyList<PinDescriptor> InputPins => [
            new("Exec", PinType.Execution, 20),
            new("Name", PinType.String, 35),
            new("Source", PinType.String, 35)
        ];

        public IReadOnlyList<PinDescriptor> OutputPins => [
            new("Exec", PinType.Execution, 20),
            new("Return", PinType.String, 40)
        ];

        public BlockStatement? ExtractStatement(BSCall invoke, int lineNumber, string? exprText) => null;

        public BlueprintNode ConfigureNode(BlueprintNode node, CFGStatement stmt)
        {
            if (node is BuiltinFunctionNode bfn && stmt.Arguments?.Count > 0)
                bfn.Properties["Name"] = stmt.Arguments[0];
            return node;
        }

        public BlockStatement? ToStatement(BlueprintNode node, INodeExportHelper helper)
        {
            var name = helper.GetInputValue(node, "Name");
            var source = helper.GetInputValue(node, "Source");
            var expr = $"{FunctionName}({name}, {source})";
            var pubVar = helper.GetOutputPubVar(node, "Return");
            return new ExpressionStatement
            {
                Expression = expr,
                SourceCode = string.IsNullOrEmpty(pubVar) ? $"{expr};" : $"{pubVar} = {expr};",
                LineNumber = 1
            };
        }

        public IEnumerable<OutputArmDescriptor> GetOutputArms() => [];
    }
}

namespace KitX.Workflow.BlockScripting
{
    public partial class BlockScriptExecutionGlobals
    {
        public string CreateWorkflow(string name, string blockScriptSource)
        {
            if (string.IsNullOrEmpty(name) || string.IsNullOrEmpty(blockScriptSource)) return "";
            if (!ServiceLocator.IsInitialized) return "";
            try
            {
                var storage = ServiceLocator.GetRequiredService<IWorkflowStorageService>();
                var workflowId = Guid.NewGuid().ToString();
                var kcsData = new KcsFileFormat
                {
                    Id = workflowId,
                    Name = name,
                    CreatedTime = DateTime.UtcNow,
                    LastModifiedTime = DateTime.UtcNow,
                    UseBlockMode = true,
                    BlockScriptSource = blockScriptSource,
                    Author = "AI Assistant",
                    Description = "Workflow generated by KitX AI Assistant"
                };

                storage.SaveWorkflowDataAsync(workflowId, kcsData).GetAwaiter().GetResult();
                Log.Information("[BlockScriptGlobals] CreateWorkflow: {Id} '{Name}'", workflowId, name);
                return workflowId;
            }
            catch (Exception ex)
            {
                Log.Error(ex, "[BlockScriptGlobals] CreateWorkflow failed for '{Name}'", name);
                return "";
            }
        }
    }
}
